name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name : apt packages
      run: |
        sudo apt update
        sudo apt install -y cppcheck valgrind

    - name: cppcheck
      run: cppcheck --enable=all simple.c

    - name: make all
      run: make all

    - name: valgrind
      run: valgrind ./all.out
